(function(global){'use strict';
const L=(zh,en,vi,ja)=>({zh,en,vi,ja});
const M1=L('固有数词1～10','Native Korean numbers 1–10','Số thuần Hàn 1–10','固有数詞1～10'),M2=L('与개一起计数','Counting with 개','Đếm với 개','개で数える'),M3=L('数量挑战','Quantity challenge','Thử thách số lượng','数量チャレンジ');
global.NikigoLessonConfig={id:'lesson-13',displayNumber:13,name:L('第13课 · 固有数词1～10与基础数量','Lesson 13 · Native Korean Numbers 1–10 and Basic Quantities','Bài 13 · Số thuần Hàn 1–10 và số lượng cơ bản','第13課 · 固有数詞1～10と基本数量'),steps:[
{id:'intro',type:'intro',module:M1,tag:L('K1 · 第13课','K1 · LESSON 13','K1 · BÀI 13','K1 · 第13課'),title:L('用固有数词数到十','Count to ten with native Korean numbers','Đếm đến mười bằng số thuần Hàn','固有数詞で10まで数える'),lead:L('只学习固有数词1～10、计数单位개和基础数量问答。','Learn only native Korean numbers 1–10, the counter 개, and basic quantity questions and answers.','Chỉ học số thuần Hàn 1–10, đơn vị đếm 개 và hỏi đáp số lượng cơ bản.','固有数詞1～10、助数詞개、基本的な数量の質問と答えだけを学びます。'),items:[{title:L('1～5','1–5','1–5','1～5'),text:'하나 · 둘 · 셋 · 넷 · 다섯'},{title:L('6～10','6–10','6–10','6～10'),text:'여섯 · 일곱 · 여덟 · 아홉 · 열'},{title:L('基础问答','Basic exchange','Hỏi đáp cơ bản','基本問答'),text:'몇 개예요? · 세 개예요.'}]},
{id:'one-five',type:'concept',module:M1,tag:L('数字卡片','NUMBER CARDS','THẺ SỐ','数字カード'),title:L('先认识一到五','Meet one through five','Làm quen từ một đến năm','まず1から5'),lead:L('观察数字与固有数词的对应。','Observe each digit and its native Korean number.','Quan sát sự tương ứng giữa chữ số và số thuần Hàn.','数字と固有数詞の対応を見ます。'),items:[{title:'1',korean:'하나',detail:L('一','one','một','一')},{title:'2',korean:'둘',detail:L('二','two','hai','二')},{title:'3',korean:'셋',detail:L('三','three','ba','三')},{title:'4',korean:'넷',detail:L('四','four','bốn','四')},{title:'5',korean:'다섯',detail:L('五','five','năm','五')}]},
{id:'match-one-five',type:'match',module:M1,tag:L('配对','MATCH','GHÉP','マッチ'),title:L('把一到五配到数字','Match one through five to digits','Ghép số một đến năm với chữ số','1から5を数字に合わせる'),lead:L('按刚才的数词卡片完成配对。','Use the number cards you just studied.','Dùng các thẻ số vừa học để ghép.','先ほどの数字カードを使います。'),pairs:[{id:'one',leftKorean:'하나',right:'1'},{id:'two',leftKorean:'둘',right:'2'},{id:'three',leftKorean:'셋',right:'3'},{id:'four',leftKorean:'넷',right:'4'},{id:'five',leftKorean:'다섯',right:'5'}],explanation:L('하나、둘、셋、넷、다섯依次对应1～5。','하나, 둘, 셋, 넷, 다섯 correspond to 1–5.','하나, 둘, 셋, 넷, 다섯 lần lượt là 1–5.','하나・둘・셋・넷・다섯は1～5です。')},
{id:'six-ten',type:'concept',module:M1,tag:L('数字卡片','NUMBER CARDS','THẺ SỐ','数字カード'),title:L('继续认识六到十','Continue with six through ten','Tiếp tục từ sáu đến mười','6から10へ進む'),lead:L('这仍然是固有数词，不引入汉字数词。','These are still native Korean numbers; Sino-Korean numbers are not introduced.','Đây vẫn là số thuần Hàn; không giới thiệu số Hán Hàn.','引き続き固有数詞です。漢数詞は導入しません。'),items:[{title:'6',korean:'여섯',detail:L('六','six','sáu','六')},{title:'7',korean:'일곱',detail:L('七','seven','bảy','七')},{title:'8',korean:'여덟',detail:L('八','eight','tám','八')},{title:'9',korean:'아홉',detail:L('九','nine','chín','九')},{title:'10',korean:'열',detail:L('十','ten','mười','十')}]},
{id:'identify-eight',type:'choice',module:M1,tag:L('选择','CHOOSE','CHỌN','選択'),title:L('哪个固有数词表示8？','Which native Korean number means 8?','Số thuần Hàn nào nghĩa là 8?','8を表す固有数詞は？'),lead:L('只在六到十中选择。','Choose only from six through ten.','Chỉ chọn trong nhóm sáu đến mười.','6から10の中から選びます。'),options:[{id:'eight',korean:'여덟'},{id:'seven',korean:'일곱'},{id:'nine',korean:'아홉'}],correct:'eight',explanation:L('여덟表示8。','여덟 means 8.','여덟 nghĩa là 8.','여덟は8です。')},
{id:'match-six-ten',type:'match',module:M1,tag:L('配对','MATCH','GHÉP','マッチ'),title:L('把六到十配到数字','Match six through ten to digits','Ghép số sáu đến mười với chữ số','6から10を数字に合わせる'),lead:L('完成第二组数词配对。','Complete the second number set.','Hoàn thành nhóm số thứ hai.','2つ目の数詞グループを完成します。'),pairs:[{id:'six',leftKorean:'여섯',right:'6'},{id:'seven',leftKorean:'일곱',right:'7'},{id:'eight',leftKorean:'여덟',right:'8'},{id:'nine',leftKorean:'아홉',right:'9'},{id:'ten',leftKorean:'열',right:'10'}],explanation:L('여섯到열依次对应6～10。','여섯 through 열 correspond to 6–10.','여섯 đến 열 lần lượt là 6–10.','여섯から열は6～10です。')},
{id:'counter-forms',type:'concept',module:M2,tag:L('与개搭配','WITH 개','KẾT HỢP VỚI 개','개との組み合わせ'),title:L('一到四在개前变为한、두、세、네','Before 개, 1–4 become 한, 두, 세, 네','Trước 개, 1–4 thành 한, 두, 세, 네','개の前で1～4は한・두・세・네になる'),lead:L('本课只学习这四个计数形式，不扩展复杂音变或其他量词。','Learn only these four counting forms; no complex sound changes or other counters are added.','Chỉ học bốn dạng đếm này; không mở rộng biến âm phức tạp hay đơn vị khác.','この4つの数え方だけを学び、複雑な音変化や他の助数詞には広げません。'),items:[{title:'하나 → 한',korean:'한 개',detail:L('一个','one item','một cái','一つ')},{title:'둘 → 두',korean:'두 개',detail:L('两个','two items','hai cái','二つ')},{title:'셋 → 세',korean:'세 개',detail:L('三个','three items','ba cái','三つ')},{title:'넷 → 네',korean:'네 개',detail:L('四个','four items','bốn cái','四つ')}]},
{id:'match-counter',type:'match',module:M2,tag:L('形式配对','FORM MATCH','GHÉP DẠNG','形のマッチ'),title:L('把原形配到개前形式','Match base forms to forms before 개','Ghép dạng gốc với dạng trước 개','元の形と개の前の形を合わせる'),lead:L('注意只改变一到四。','Only one through four change here.','Chỉ từ một đến bốn thay đổi.','ここで変わるのは1から4だけです。'),pairs:[{id:'one',leftKorean:'하나',right:'한 개'},{id:'two',leftKorean:'둘',right:'두 개'},{id:'three',leftKorean:'셋',right:'세 개'},{id:'four',leftKorean:'넷',right:'네 개'}],explanation:L('개前使用한、두、세、네。','Use 한, 두, 세, 네 before 개.','Dùng 한, 두, 세, 네 trước 개.','개の前では한・두・세・네を使います。')},
{id:'build-one',type:'build',module:M2,tag:L('拼合','BUILD','GHÉP','組み立て'),title:L('拼出“一个”','Build “one item”','Ghép “một cái”','「一つ」を作る'),lead:L('选择正确的计数形式、개和礼貌结尾。','Choose the counting form, 개, and polite ending.','Chọn dạng đếm, 개 và đuôi lịch sự.','正しい数え方・개・丁寧な語尾を選びます。'),groups:[{id:'number',label:L('数量','Quantity','Số lượng','数量'),correct:'han',options:[{id:'han',korean:'한'},{id:'hana',korean:'하나'}]},{id:'counter',label:L('单位','Counter','Đơn vị','助数詞'),correct:'gae',options:[{id:'gae',korean:'개'},{id:'myeong',korean:'명'}]},{id:'ending',label:L('结尾','Ending','Kết thúc','語尾'),correct:'yeyo',options:[{id:'yeyo',korean:'예요'},{id:'ieyo',korean:'이에요'}]}],explanation:L('本课的完整回答是한 개예요。','The complete answer here is 한 개예요.','Câu trả lời hoàn chỉnh là 한 개예요.','完全な答えは한 개예요です。')},
{id:'how-many',type:'scenario',module:M2,tag:L('数量问答','QUANTITY EXCHANGE','HỎI ĐÁP SỐ LƯỢNG','数量問答'),title:L('“몇 개예요?”应选哪个“三个”的回答？','Which answer gives “three” to 몇 개예요?','Câu nào trả lời “ba cái” cho 몇 개예요?','「몇 개예요?」に「三つ」と答える文は？'),lead:L('选择数词在개前的正确形式。','Choose the correct number form before 개.','Chọn đúng dạng số trước 개.','개の前の正しい数詞を選びます。'),context:[{role:'A',korean:'몇 개예요?'}],options:[{id:'three',korean:'세 개예요.'},{id:'base',korean:'셋 개예요.'},{id:'people',korean:'세 명이에요.'}],correct:'three',explanation:L('셋在개前变为세，所以说세 개예요。','셋 becomes 세 before 개, so say 세 개예요.','셋 thành 세 trước 개, nên nói 세 개예요.','셋は개の前で세になるため、세 개예요です。')},
{id:'five-ten',type:'match',module:M3,tag:L('数量配对','QUANTITY MATCH','GHÉP SỐ LƯỢNG','数量マッチ'),title:L('五到十与개一起使用','Use five through ten with 개','Dùng từ năm đến mười với 개','5から10を개と使う'),lead:L('五以上保持本课所学的数词形式。','From five onward, keep the number forms learned here.','Từ năm trở lên giữ dạng số đã học.','5以上は学んだ数詞の形を保ちます。'),pairs:[{id:'five',leftKorean:'다섯',right:'다섯 개'},{id:'six',leftKorean:'여섯',right:'여섯 개'},{id:'eight',leftKorean:'여덟',right:'여덟 개'},{id:'ten',leftKorean:'열',right:'열 개'}],explanation:L('다섯、여섯、여덟、열可直接放在개前。','다섯, 여섯, 여덟, and 열 can stand directly before 개.','다섯, 여섯, 여덟 và 열 đứng trực tiếp trước 개.','다섯・여섯・여덟・열はそのまま개の前に置けます。')},
{id:'final-challenge',type:'scenario',module:M3,tag:L('综合挑战','INTEGRATED CHALLENGE','THỬ THÁCH TỔNG HỢP','総合チャレンジ'),title:L('哪组问答完全符合本课？','Which exchange stays fully within this lesson?','Đoạn hỏi đáp nào hoàn toàn đúng phạm vi bài?','本課の範囲に完全に合う問答は？'),lead:L('只判断固有数词1～10、개和礼貌数量问答。','Judge only native Korean numbers 1–10, 개, and the polite quantity exchange.','Chỉ xét số thuần Hàn 1–10, 개 và hỏi đáp số lượng lịch sự.','固有数詞1～10・개・丁寧な数量問答だけで判断します。'),options:[{id:'right',label:L('A: 몇 개예요? / B: 열 개예요.','A: 몇 개예요? / B: 열 개예요.','A: 몇 개예요? / B: 열 개예요.','A: 몇 개예요? / B: 열 개예요.')},{id:'sino',label:L('使用汉字数词计算价格','Use Sino-Korean numbers for prices','Dùng số Hán Hàn để tính giá','漢数詞で価格を数える')},{id:'counter',label:L('使用명、살、시等其他量词','Use other counters such as 명, 살, or 시','Dùng đơn vị khác như 명, 살 hoặc 시','명・살・시など他の助数詞を使う')}],correct:'right',explanation:L('正确项只使用本课的固有数词、개和礼貌요体。','The correct exchange uses only a native number, 개, and polite 요-style.','Đoạn đúng chỉ dùng số thuần Hàn, 개 và lối nói lịch sự 요.','正解は固有数詞・개・丁寧な요体だけを使います。')},
{id:'complete',type:'complete',module:M3,tag:L('K1 · 第13课完成','K1 · LESSON 13 COMPLETE','K1 · HOÀN THÀNH BÀI 13','K1 · 第13課完了'),title:L('第13课完成！','Lesson 13 complete!','Đã hoàn thành Bài 13!','第13課完了！'),lead:L('你已经能识别固有数词1～10，并使用개完成基础数量问答。','You can recognize native Korean numbers 1–10 and use 개 in a basic quantity exchange.','Bạn đã có thể nhận biết số thuần Hàn 1–10 và dùng 개 trong hỏi đáp số lượng cơ bản.','固有数詞1～10を識別し、개を使った基本的な数量問答ができます。')}
]};
})(window);
