(function (global) {
  'use strict';

  const LESSON_ID = 'lesson-06';
  const PREREQUISITE = 'lesson-05';
  const SESSION_KEY = `nikigoLessonSession:${LESSON_ID}`;
  const LANGUAGES = ['zh', 'en', 'vi', 'ja'];
  const SCREENS = ['intro','review','structure','oa','ueo','i-family','combine-practice','carrier','builder','split','near-group','spelling-practice','extended','words','challenge','retry','summary','complete'];
  const COMPOUND_VOWELS = ['ㅒ','ㅖ','ㅘ','ㅙ','ㅚ','ㅝ','ㅞ','ㅟ','ㅢ'];
  const COMBINATIONS = Object.freeze({
    'ㅑ+ㅣ':'ㅒ','ㅕ+ㅣ':'ㅖ','ㅗ+ㅏ':'ㅘ','ㅗ+ㅐ':'ㅙ','ㅗ+ㅣ':'ㅚ','ㅜ+ㅓ':'ㅝ','ㅜ+ㅔ':'ㅞ','ㅜ+ㅣ':'ㅟ','ㅡ+ㅣ':'ㅢ'
  });
  const CARRIERS = Object.freeze({'ㅒ':'얘','ㅖ':'예','ㅘ':'와','ㅙ':'왜','ㅚ':'외','ㅝ':'워','ㅞ':'웨','ㅟ':'위','ㅢ':'의'});
  const SAFE_SYLLABLES = Object.freeze({'ㅇ+ㅘ':'와','ㅇ+ㅙ':'왜','ㅇ+ㅚ':'외','ㅇ+ㅝ':'워','ㅇ+ㅞ':'웨','ㅇ+ㅟ':'위','ㅇ+ㅢ':'의','ㅁ+ㅝ':'뭐'});
  const AUDIO_TEXTS = ['와','워','왜','웨','외','위','의','얘','예','뭐','과자','여우','의자'];
  const AUDIO_FILES = Object.freeze(global.NikigoAudio?.forSpeechTexts?.(AUDIO_TEXTS)?.audioFiles || {});

  const UI = {
    "zh": {
      "lessonName": "第6课 · 复合元音",
      "progress": "课程进度",
      "home": "返回学习主页",
      "back": "返回",
      "next": "继续",
      "finish": "完成课程",
      "introTag": "K0 · 第6课",
      "introTitle": "看懂并拼出复合元音",
      "introLead": "把已经认识的元音组合起来，读出完整音节，并通过拼写识别容易混淆的组合。",
      "goal1": "看见结构",
      "goal1d": "理解ㅗ、ㅜ、ㅡ如何与其他元音组合。",
      "goal2": "拼成音节",
      "goal2d": "用不发音的ㅇ承载复合元音。",
      "goal3": "阅读真实词",
      "goal3d": "只读没有收音的词，不提前学习CVC。",
      "scopeNote": "本课只学习元音和CV音节，不出现收音。现代首尔韩语中有些拼写的发音非常接近，本课不会制造夸大的听辨差异。",
      "reviewTag": "快速复习",
      "reviewTitle": "ㅐ和ㅔ已经学过",
      "reviewLead": "它们是后面ㅙ、ㅞ以及ㅒ、ㅖ的拼写基础。现代口语中ㅐ和ㅔ也常常很接近。",
      "structureTag": "结构地图",
      "structureTitle": "复合元音由两个元音部分组成",
      "structureLead": "先看左边或上方的基础元音，再看第二个元音部分。拼写结构比罗马音更可靠。",
      "oaTitle": "从ㅗ + ㅏ得到ㅘ",
      "oaLead": "把ㅏ放进ㅗ的结构中，形成ㅘ；加上不发音的ㅇ，写成完整音节와。",
      "ueoTitle": "从ㅜ + ㅓ得到ㅝ",
      "ueoLead": "把ㅓ放进ㅜ的结构中，形成ㅝ；加上ㅇ，写成完整音节워。",
      "familyTitle": "再看三个带ㅣ的组合",
      "familyLead": "ㅚ、ㅟ、ㅢ分别保留ㅗ、ㅜ、ㅡ的结构线索。",
      "combineTag": "互动 · 组合",
      "combineTitle": "点击正确的组合结果",
      "combineLead": "全部答对后继续。这里只检查拼写结构，不进行虚假听辨。",
      "correct": "答对了！",
      "incorrect": "再看一次。正确答案是 {answer}。",
      "carrierTag": "完整音节",
      "carrierTitle": "独立书写时，用不发音的ㅇ承载元音",
      "carrierLead": "例如ㅘ写成音节时是와。这里的ㅇ只占初声位置，不发ng音。",
      "listenSyllable": "听完整音节 {text}",
      "listenWord": "听完整单词 {text}",
      "audioPending": "音频待生成/待审核",
      "audioNote": "当前没有完全匹配且已审核的托管音频，因此按钮保持禁用；不会使用设备TTS、相似文字或答案替代。",
      "builderTag": "互动 · 拼合器",
      "builderTitle": "把初声和复合元音放进一个音节块",
      "builderLead": "拼出至少3个不同音节，其中必须包含뭐。系统只允许本课范围内的安全组合。",
      "initial": "初声",
      "vowel": "复合元音",
      "build": "确认拼合 {text}",
      "unsupported": "这个组合不在本课练习范围内",
      "built": "已经拼出",
      "builderNeed": "还需要拼出3个不同音节，并包含뭐。",
      "splitTag": "互动 · 拆分",
      "splitTitle": "把完整音节拆回复合元音结构",
      "splitLead": "识别初声和复合元音，不加入收音。",
      "nearTag": "拼写近似组",
      "nearTitle": "ㅙ、ㅚ、ㅞ重点看拼写",
      "nearLead": "在现代首尔韩语中，这三个元音的实际发音可能非常接近。真实说话人也未必保持明显差异。",
      "noFakeListening": "因此本课不设置“必须听出ㅙ、ㅚ、ㅞ差异”的题，只练习它们的字形来源。",
      "spellingTag": "互动 · 拼写",
      "spellingTitle": "根据结构选择正确拼写",
      "spellingLead": "用组成部分判断，不靠夸大的声音差异。",
      "extendedTag": "延伸辨认",
      "extendedTitle": "ㅒ和ㅖ也以拼写识别为主",
      "extendedLead": "ㅒ由ㅑ + ㅣ组成，ㅖ由ㅕ + ㅣ组成；现代实际发音常接近ㅐ、ㅔ。重点识别拼写，不强迫听出夸大的差异。",
      "extendedNote": "看到얘、예时先认清拼写即可，不要求一次课程就听出人为放大的差别。",
      "wordsTag": "无收音词汇",
      "wordsTitle": "读出不带收音的真实词",
      "wordsLead": "这些词只使用已学辅音、元音和CV音节。우유和와요涉及尚未系统练习的ㅠ、ㅛ或礼貌语法，本课不作为必学词。",
      "snack": "零食",
      "fox": "狐狸",
      "chair": "椅子",
      "why": "为什么",
      "yes": "是/好的",
      "what": "什么",
      "challengeTag": "5题挑战",
      "challengeTitle": "检查复合元音的拼写与结构",
      "challengeLead": "题目只检查结构、音节和无收音词汇，不要求辨认被夸大的声音差异。",
      "startChallenge": "开始挑战",
      "question": "挑战题",
      "c1": "ㅗ + ㅏ组成哪个复合元音？",
      "c2": "ㅝ可以拆成哪两个元音部分？",
      "c3": "ㅟ加上不发音的ㅇ后写成哪个音节？",
      "c4": "哪一组在本课只做拼写辨认，不强制听辨？",
      "c5": "哪个无收音词表示“零食”？",
      "c4correct": "ㅙ / ㅚ / ㅞ",
      "correctAnswer": "正确答案",
      "previousQuestion": "上一题",
      "nextQuestion": "下一题",
      "retryTag": "错题重练",
      "retryTitle": "再练一次容易混淆的结构",
      "retryLead": "答错的题会保留到这里，改正后再进入总结。",
      "retryEmpty": "没有需要重练的题。",
      "tryAgain": "再试一次",
      "remaining": "还需重练 {count} 题",
      "summaryTag": "课程总结",
      "summaryTitle": "你已经能识别复合元音结构",
      "summaryLead": "先看拼写结构，再放进完整音节和无收音词中阅读。",
      "summary1": "ㅗ、ㅜ、ㅡ可以与其他元音组合。",
      "summary2": "复合元音独立成音节时用不发音的ㅇ占位。",
      "summary3": "ㅙ、ㅚ、ㅞ的现代发音可能非常接近。",
      "summary4": "ㅒ、ㅖ重点识别拼写，不夸大发音差别。",
      "summary5": "本课只有元音和CV结构；收音留到第7课。",
      "completeTag": "K0 · 第6课完成",
      "completeTitle": "第6课完成！",
      "completeLead": "你已经完成复合元音的构成、拼写、拼合和无收音词阅读。",
      "xpEarned": "本次获得 +50 XP",
      "xpAlreadyClaimed": "首次完成奖励已领取，本次不重复发放XP",
      "progressSaved": "学习进度已保存",
      "returnCourses": "返回课程主页",
      "lockedTitle": "完成第5课后开放",
      "lockedLead": "请先完成“看懂韩语音节块”，再学习复合元音。"
    },
    "en": {
      "lessonName": "Lesson 6 · Compound Vowels",
      "progress": "Lesson progress",
      "home": "Return to learning home",
      "back": "Back",
      "next": "Continue",
      "finish": "Complete lesson",
      "introTag": "K0 · LESSON 6",
      "introTitle": "Recognize and build compound vowels",
      "introLead": "Combine familiar vowel parts, read full syllables, and use spelling to identify easily confused forms.",
      "goal1": "See the structure",
      "goal1d": "Understand how ㅗ, ㅜ and ㅡ combine with other vowels.",
      "goal2": "Build syllables",
      "goal2d": "Use silent onset ㅇ to carry compound vowels.",
      "goal3": "Read real words",
      "goal3d": "Read words without finals; CVC stays for later.",
      "scopeNote": "This lesson uses vowels and CV syllables only. Some spellings sound very close in modern Seoul Korean, so we do not invent exaggerated listening differences.",
      "reviewTag": "QUICK REVIEW",
      "reviewTitle": "You already know ㅐ and ㅔ",
      "reviewLead": "They support the spellings of ㅙ, ㅞ, ㅒ and ㅖ. In modern speech, ㅐ and ㅔ are also often very close.",
      "structureTag": "STRUCTURE MAP",
      "structureTitle": "A compound vowel contains two vowel parts",
      "structureLead": "Look for the base vowel first, then the second part. Spelling structure is more reliable than romanization.",
      "oaTitle": "Build ㅘ from ㅗ + ㅏ",
      "oaLead": "Place ㅏ into the ㅗ structure to make ㅘ. With silent ㅇ, the full syllable is 와.",
      "ueoTitle": "Build ㅝ from ㅜ + ㅓ",
      "ueoLead": "Place ㅓ into the ㅜ structure to make ㅝ. With ㅇ, the full syllable is 워.",
      "familyTitle": "Three more combinations with ㅣ",
      "familyLead": "ㅚ, ㅟ and ㅢ preserve visual clues from ㅗ, ㅜ and ㅡ.",
      "combineTag": "INTERACT · COMBINE",
      "combineTitle": "Choose the correct combined vowel",
      "combineLead": "Answer every item correctly. This checks spelling structure, not fake listening distinctions.",
      "correct": "Correct!",
      "incorrect": "Look again. The correct answer is {answer}.",
      "carrierTag": "FULL SYLLABLES",
      "carrierTitle": "Use silent ㅇ when writing the vowel as a syllable",
      "carrierLead": "For example, ㅘ becomes 와 in a full syllable. Initial ㅇ holds the place and is not pronounced ng.",
      "listenSyllable": "Listen to full syllable {text}",
      "listenWord": "Listen to full word {text}",
      "audioPending": "Audio pending generation/review",
      "audioNote": "No exact, reviewed hosted match is available yet. Buttons stay disabled; device TTS, similar text, and answer substitution are not used.",
      "builderTag": "INTERACT · BUILDER",
      "builderTitle": "Put an onset and compound vowel into one block",
      "builderLead": "Build at least 3 different syllables and include 뭐. Only safe combinations from this lesson are allowed.",
      "initial": "Onset",
      "vowel": "Compound vowel",
      "build": "Confirm syllable {text}",
      "unsupported": "This combination is outside this lesson",
      "built": "Built",
      "builderNeed": "Build 3 different syllables and include 뭐.",
      "splitTag": "INTERACT · SPLIT",
      "splitTitle": "Split a full syllable back into its compound vowel",
      "splitLead": "Identify the onset and compound vowel. No final is added.",
      "nearTag": "CLOSE SPELLINGS",
      "nearTitle": "Focus on spelling for ㅙ, ㅚ and ㅞ",
      "nearLead": "In modern Seoul Korean, these three vowels can sound very close. Real speakers may not keep a strong distinction.",
      "noFakeListening": "This lesson therefore does not force you to hear a difference among ㅙ, ㅚ and ㅞ. It practices their written origins.",
      "spellingTag": "INTERACT · SPELLING",
      "spellingTitle": "Choose the spelling from its structure",
      "spellingLead": "Use the components, not exaggerated audio differences.",
      "extendedTag": "EXTENDED FORMS",
      "extendedTitle": "Treat ㅒ and ㅖ mainly as spelling recognition",
      "extendedLead": "ㅒ is built from ㅑ + ㅣ, and ㅖ from ㅕ + ㅣ. In modern speech they are often close to ㅐ and ㅔ, so focus on spelling rather than an exaggerated listening contrast.",
      "extendedNote": "For 얘 and 예, recognize the spelling first. One lesson should not promise an artificial listening distinction.",
      "wordsTag": "WORDS WITHOUT FINALS",
      "wordsTitle": "Read real words with no final consonants",
      "wordsLead": "These use learned consonants, vowels and CV syllables. 우유 and 와요 are not required because ㅠ, ㅛ or polite-ending grammar have not been practiced systematically.",
      "snack": "snack",
      "fox": "fox",
      "chair": "chair",
      "why": "why",
      "yes": "yes/okay",
      "what": "what",
      "challengeTag": "5-QUESTION CHALLENGE",
      "challengeTitle": "Check compound-vowel spelling and structure",
      "challengeLead": "Questions cover structure, syllables and words without finals. No exaggerated listening distinction is required.",
      "startChallenge": "Start challenge",
      "question": "Challenge",
      "c1": "Which compound vowel comes from ㅗ + ㅏ?",
      "c2": "Which two vowel parts make ㅝ?",
      "c3": "Which syllable is ㅟ with silent onset ㅇ?",
      "c4": "Which group is spelling-only here, with no forced listening distinction?",
      "c5": "Which word without a final means “snack”?",
      "c4correct": "ㅙ / ㅚ / ㅞ",
      "correctAnswer": "Correct answer",
      "previousQuestion": "Previous question",
      "nextQuestion": "Next question",
      "retryTag": "RETRY",
      "retryTitle": "Practice confusing structures again",
      "retryLead": "Missed questions remain here. Correct them before the summary.",
      "retryEmpty": "No questions need another round.",
      "tryAgain": "Try again",
      "remaining": "{count} question(s) left",
      "summaryTag": "SUMMARY",
      "summaryTitle": "You can recognize compound-vowel structures",
      "summaryLead": "Read the spelling structure first, then place it in full syllables and words without finals.",
      "summary1": "ㅗ, ㅜ and ㅡ can combine with other vowels.",
      "summary2": "A vowel-only syllable uses silent onset ㅇ.",
      "summary3": "ㅙ, ㅚ and ㅞ may sound very close today.",
      "summary4": "ㅒ and ㅖ focus on spelling, not exaggerated sound differences.",
      "summary5": "This lesson stays with vowels and CV; finals begin in Lesson 7.",
      "completeTag": "K0 · LESSON 6 COMPLETE",
      "completeTitle": "Lesson 6 complete!",
      "completeLead": "You completed compound-vowel structure, spelling, building and word reading.",
      "xpEarned": "You earned +50 XP this time",
      "xpAlreadyClaimed": "The first-completion reward was already claimed; no extra XP this time",
      "progressSaved": "Learning progress saved",
      "returnCourses": "Return to Courses",
      "lockedTitle": "Opens after Lesson 5",
      "lockedLead": "Complete “Understand Korean Syllable Blocks” before compound vowels."
    },
    "vi": {
      "lessonName": "Bài 6 · Nguyên âm ghép",
      "progress": "Tiến độ bài học",
      "home": "Về trang học tập",
      "back": "Quay lại",
      "next": "Tiếp tục",
      "finish": "Hoàn thành bài",
      "introTag": "K0 · BÀI 6",
      "introTitle": "Nhận biết và ghép nguyên âm ghép",
      "introLead": "Kết hợp các phần nguyên âm quen thuộc, đọc âm tiết đầy đủ và nhận biết chữ viết dễ nhầm.",
      "goal1": "Nhìn cấu trúc",
      "goal1d": "Hiểu cách ㅗ, ㅜ, ㅡ kết hợp với nguyên âm khác.",
      "goal2": "Ghép âm tiết",
      "goal2d": "Dùng ㅇ câm để mang nguyên âm ghép.",
      "goal3": "Đọc từ thật",
      "goal3d": "Chỉ đọc từ không có âm cuối; CVC để học sau.",
      "scopeNote": "Bài này chỉ có nguyên âm và âm tiết CV. Một số cách viết nghe rất gần nhau trong tiếng Hàn Seoul hiện đại nên không tạo bài nghe phân biệt giả.",
      "reviewTag": "ÔN NHANH",
      "reviewTitle": "Bạn đã học ㅐ và ㅔ",
      "reviewLead": "Chúng giúp hiểu cách viết ㅙ, ㅞ, ㅒ và ㅖ. Trong lời nói hiện đại, ㅐ và ㅔ cũng thường rất gần nhau.",
      "structureTag": "BẢN ĐỒ CẤU TRÚC",
      "structureTitle": "Nguyên âm ghép có hai phần nguyên âm",
      "structureLead": "Tìm nguyên âm nền trước rồi phần thứ hai. Cấu trúc chữ viết đáng tin hơn phiên âm.",
      "oaTitle": "Ghép ㅘ từ ㅗ + ㅏ",
      "oaLead": "Đặt ㅏ vào cấu trúc ㅗ để thành ㅘ. Với ㅇ câm, âm tiết đầy đủ là 와.",
      "ueoTitle": "Ghép ㅝ từ ㅜ + ㅓ",
      "ueoLead": "Đặt ㅓ vào cấu trúc ㅜ để thành ㅝ. Với ㅇ, âm tiết đầy đủ là 워.",
      "familyTitle": "Ba tổ hợp khác với ㅣ",
      "familyLead": "ㅚ, ㅟ, ㅢ giữ dấu hiệu hình dạng của ㅗ, ㅜ, ㅡ.",
      "combineTag": "TƯƠNG TÁC · GHÉP",
      "combineTitle": "Chọn nguyên âm ghép đúng",
      "combineLead": "Trả lời đúng tất cả. Đây là kiểm tra chữ viết, không phải nghe phân biệt giả.",
      "correct": "Chính xác!",
      "incorrect": "Hãy xem lại. Đáp án đúng là {answer}.",
      "carrierTag": "ÂM TIẾT ĐẦY ĐỦ",
      "carrierTitle": "Dùng ㅇ câm khi viết nguyên âm thành âm tiết",
      "carrierLead": "Ví dụ ㅘ trở thành 와. ㅇ đầu chỉ giữ chỗ và không đọc thành ng.",
      "listenSyllable": "Nghe âm tiết đầy đủ {text}",
      "listenWord": "Nghe từ đầy đủ {text}",
      "audioPending": "Âm thanh chờ tạo/duyệt",
      "audioNote": "Chưa có tệp lưu trữ khớp chính xác và đã duyệt. Nút bị vô hiệu; không dùng TTS thiết bị, văn bản gần giống hay đáp án thay thế.",
      "builderTag": "TƯƠNG TÁC · GHÉP KHỐI",
      "builderTitle": "Đặt phụ âm đầu và nguyên âm ghép vào một khối",
      "builderLead": "Ghép ít nhất 3 âm tiết khác nhau và có 뭐. Chỉ cho phép tổ hợp an toàn trong bài.",
      "initial": "Phụ âm đầu",
      "vowel": "Nguyên âm ghép",
      "build": "Xác nhận âm tiết {text}",
      "unsupported": "Tổ hợp này ngoài phạm vi bài",
      "built": "Đã ghép",
      "builderNeed": "Ghép 3 âm tiết khác nhau và có 뭐.",
      "splitTag": "TƯƠNG TÁC · TÁCH",
      "splitTitle": "Tách âm tiết về nguyên âm ghép",
      "splitLead": "Nhận biết phụ âm đầu và nguyên âm ghép, không thêm âm cuối.",
      "nearTag": "NHÓM GẦN NHAU",
      "nearTitle": "Tập trung chữ viết của ㅙ, ㅚ, ㅞ",
      "nearLead": "Trong tiếng Hàn Seoul hiện đại, ba nguyên âm này có thể nghe rất gần nhau.",
      "noFakeListening": "Vì vậy bài không ép nghe ra khác biệt ㅙ, ㅚ, ㅞ mà luyện nguồn gốc chữ viết.",
      "spellingTag": "TƯƠNG TÁC · CHÍNH TẢ",
      "spellingTitle": "Chọn chữ viết từ cấu trúc",
      "spellingLead": "Dựa vào thành phần, không dựa vào âm thanh phóng đại.",
      "extendedTag": "MỞ RỘNG",
      "extendedTitle": "ㅒ và ㅖ chủ yếu để nhận biết chữ viết",
      "extendedLead": "ㅒ được ghép từ ㅑ + ㅣ, còn ㅖ từ ㅕ + ㅣ. Cách phát âm hiện đại thường gần ㅐ, ㅔ nên tập trung vào chữ viết, không ép nghe khác biệt phóng đại.",
      "extendedNote": "Với 얘 và 예, trước hết nhận đúng chữ. Không hứa phân biệt nghe giả sau một bài.",
      "wordsTag": "TỪ KHÔNG ÂM CUỐI",
      "wordsTitle": "Đọc từ thật không có âm cuối",
      "wordsLead": "Các từ chỉ dùng phụ âm, nguyên âm và CV đã học. 우유 và 와요 không bắt buộc vì ㅠ, ㅛ hoặc ngữ pháp lịch sự chưa được luyện hệ thống.",
      "snack": "đồ ăn vặt",
      "fox": "cáo",
      "chair": "ghế",
      "why": "tại sao",
      "yes": "vâng/được",
      "what": "cái gì",
      "challengeTag": "THỬ THÁCH 5 CÂU",
      "challengeTitle": "Kiểm tra cấu trúc và chữ viết",
      "challengeLead": "Câu hỏi về cấu trúc, âm tiết và từ không âm cuối; không ép nghe khác biệt phóng đại.",
      "startChallenge": "Bắt đầu",
      "question": "Thử thách",
      "c1": "Nguyên âm nào tạo từ ㅗ + ㅏ?",
      "c2": "Hai phần nào tạo ㅝ?",
      "c3": "ㅟ với ㅇ câm tạo âm tiết nào?",
      "c4": "Nhóm nào chỉ nhận biết chữ viết, không ép nghe phân biệt?",
      "c5": "Từ không âm cuối nào nghĩa là “đồ ăn vặt”?",
      "c4correct": "ㅙ / ㅚ / ㅞ",
      "correctAnswer": "Đáp án đúng",
      "previousQuestion": "Câu trước",
      "nextQuestion": "Câu tiếp",
      "retryTag": "LUYỆN LẠI",
      "retryTitle": "Luyện lại cấu trúc dễ nhầm",
      "retryLead": "Câu sai được giữ lại; sửa đúng trước khi tổng kết.",
      "retryEmpty": "Không có câu cần luyện lại.",
      "tryAgain": "Thử lại",
      "remaining": "Còn {count} câu",
      "summaryTag": "TỔNG KẾT",
      "summaryTitle": "Bạn đã nhận biết cấu trúc nguyên âm ghép",
      "summaryLead": "Đọc cấu trúc chữ trước rồi đặt vào âm tiết và từ không âm cuối.",
      "summary1": "ㅗ, ㅜ, ㅡ có thể kết hợp với nguyên âm khác.",
      "summary2": "Âm tiết nguyên âm dùng ㅇ câm giữ chỗ.",
      "summary3": "ㅙ, ㅚ, ㅞ hiện nay có thể nghe rất gần nhau.",
      "summary4": "ㅒ, ㅖ tập trung chữ viết, không phóng đại khác biệt âm.",
      "summary5": "Bài này chỉ có nguyên âm và CV; âm cuối bắt đầu ở Bài 7.",
      "completeTag": "K0 · HOÀN THÀNH BÀI 6",
      "completeTitle": "Đã hoàn thành Bài 6!",
      "completeLead": "Bạn đã hoàn thành cấu trúc, chữ viết, ghép và đọc từ.",
      "xpEarned": "Lần này nhận +50 XP",
      "xpAlreadyClaimed": "Đã nhận thưởng lần đầu; lần này không cộng thêm XP",
      "progressSaved": "Đã lưu tiến độ",
      "returnCourses": "Trở về Bài học",
      "lockedTitle": "Mở sau Bài 5",
      "lockedLead": "Hoàn thành bài khối âm tiết trước khi học nguyên âm ghép."
    },
    "ja": {
      "lessonName": "第6課 · 複合母音",
      "progress": "レッスン進捗",
      "home": "学習ホームへ戻る",
      "back": "戻る",
      "next": "続ける",
      "finish": "レッスン完了",
      "introTag": "K0 · 第6課",
      "introTitle": "複合母音を見分けて組み立てる",
      "introLead": "既知の母音要素を組み合わせ、完全な音節で読み、似た綴りを構造から見分けます。",
      "goal1": "構造を見る",
      "goal1d": "ㅗ・ㅜ・ㅡが他の母音と組み合わさる仕組み。",
      "goal2": "音節を作る",
      "goal2d": "無音の初声ㅇで複合母音を支える。",
      "goal3": "実際の語を読む",
      "goal3d": "終声のない語だけを読み、CVCは後で学ぶ。",
      "scopeNote": "この課は母音とCV音節だけです。現代ソウル韓国語では非常に近く聞こえる綴りもあるため、誇張した聞き分け問題は作りません。",
      "reviewTag": "クイック復習",
      "reviewTitle": "ㅐとㅔは学習済み",
      "reviewLead": "ㅙ・ㅞ・ㅒ・ㅖの綴り理解に役立ちます。現代語ではㅐとㅔも近く聞こえることが多いです。",
      "structureTag": "構造マップ",
      "structureTitle": "複合母音は2つの母音要素を持つ",
      "structureLead": "まず土台の母音、次に第2要素を見ます。ローマ字より綴り構造を優先します。",
      "oaTitle": "ㅗ + ㅏからㅘを作る",
      "oaLead": "ㅗの構造にㅏを入れてㅘ。無音のㅇを加えると完全な音節와です。",
      "ueoTitle": "ㅜ + ㅓからㅝを作る",
      "ueoLead": "ㅜの構造にㅓを入れてㅝ。ㅇを加えると完全な音節워です。",
      "familyTitle": "ㅣを含む3つの組み合わせ",
      "familyLead": "ㅚ・ㅟ・ㅢにはㅗ・ㅜ・ㅡの形の手掛かりが残ります。",
      "combineTag": "操作 · 組み合わせ",
      "combineTitle": "正しい複合母音を選ぶ",
      "combineLead": "すべて正解して進みます。綴り構造を確認し、偽の聞き分けはしません。",
      "correct": "正解です！",
      "incorrect": "もう一度確認しましょう。正解は{answer}です。",
      "carrierTag": "完全な音節",
      "carrierTitle": "音節として書くときは無音のㅇを使う",
      "carrierLead": "例えばㅘは와になります。初声ㅇは場所を埋めるだけでngとは読みません。",
      "listenSyllable": "完全な音節{text}を聞く",
      "listenWord": "単語{text}全体を聞く",
      "audioPending": "音声は生成・確認待ち",
      "audioNote": "完全一致し、確認済みのホスト音声はまだありません。ボタンは無効で、端末TTS・類似テキスト・答えの代用はしません。",
      "builderTag": "操作 · 組み立て",
      "builderTitle": "初声と複合母音を1ブロックにする",
      "builderLead": "異なる3音節以上を作り、뭐を含めます。この課の安全な組み合わせだけを許可します。",
      "initial": "初声",
      "vowel": "複合母音",
      "build": "音節{text}を確定",
      "unsupported": "この組み合わせは課の範囲外です",
      "built": "作成済み",
      "builderNeed": "異なる3音節を作り、뭐を含めてください。",
      "splitTag": "操作 · 分解",
      "splitTitle": "完全な音節を複合母音へ分解",
      "splitLead": "初声と複合母音を見分けます。終声は加えません。",
      "nearTag": "近い綴り",
      "nearTitle": "ㅙ・ㅚ・ㅞは綴りを重視",
      "nearLead": "現代ソウル韓国語では3つが非常に近く聞こえる場合があります。",
      "noFakeListening": "そのため無理に聞き分けさせず、文字の由来を練習します。",
      "spellingTag": "操作 · 綴り",
      "spellingTitle": "構造から正しい綴りを選ぶ",
      "spellingLead": "誇張した音の差ではなく構成要素を使います。",
      "extendedTag": "発展",
      "extendedTitle": "ㅒとㅖも綴り認識を中心にする",
      "extendedLead": "ㅒはㅑ + ㅣ、ㅖはㅕ + ㅣから作ります。現代発音はㅐ・ㅔに近いことが多いため、誇張した聞き分けではなく綴りを重視します。",
      "extendedNote": "얘と예はまず綴りを認識します。1回で人工的な聞き分けを約束しません。",
      "wordsTag": "終声のない語",
      "wordsTitle": "終声のない実際の語を読む",
      "wordsLead": "既習の子音・母音・CVだけを使います。ㅠ・ㅛまたは丁寧語文法を未練習のため、우유と와요は必須語にしません。",
      "snack": "お菓子",
      "fox": "キツネ",
      "chair": "椅子",
      "why": "なぜ",
      "yes": "はい",
      "what": "何",
      "challengeTag": "5問チャレンジ",
      "challengeTitle": "複合母音の綴りと構造を確認",
      "challengeLead": "構造・音節・終声のない語を確認し、誇張した聞き分けは求めません。",
      "startChallenge": "開始",
      "question": "問題",
      "c1": "ㅗ + ㅏからできる複合母音は？",
      "c2": "ㅝを構成する2つの母音要素は？",
      "c3": "ㅟに無音のㅇを加えた音節は？",
      "c4": "綴りだけを確認し、強制的に聞き分けない組は？",
      "c5": "「お菓子」を表す終声のない語は？",
      "c4correct": "ㅙ / ㅚ / ㅞ",
      "correctAnswer": "正解",
      "previousQuestion": "前の問題",
      "nextQuestion": "次の問題",
      "retryTag": "再練習",
      "retryTitle": "迷いやすい構造をもう一度",
      "retryLead": "間違えた問題を残し、正解してからまとめへ進みます。",
      "retryEmpty": "再練習はありません。",
      "tryAgain": "もう一度",
      "remaining": "残り{count}問",
      "summaryTag": "まとめ",
      "summaryTitle": "複合母音の構造を認識できました",
      "summaryLead": "まず綴り構造を見て、完全な音節と終声のない語で読みます。",
      "summary1": "ㅗ・ㅜ・ㅡは他の母音と組み合わさる。",
      "summary2": "母音だけの音節は無音のㅇを使う。",
      "summary3": "ㅙ・ㅚ・ㅞは現代語で非常に近く聞こえることがある。",
      "summary4": "ㅒ・ㅖは綴り重視で、音差を誇張しない。",
      "summary5": "この課は母音とCVだけ。終声は第7課。",
      "completeTag": "K0 · 第6課完了",
      "completeTitle": "第6課 完了！",
      "completeLead": "複合母音の構造・綴り・組み立て・語の読みを完了しました。",
      "xpEarned": "今回 +50 XPを獲得",
      "xpAlreadyClaimed": "初回報酬は受取済みです。今回はXPを追加しません",
      "progressSaved": "進捗を保存しました",
      "returnCourses": "コースへ戻る",
      "lockedTitle": "第5課完了後に開きます",
      "lockedLead": "音節ブロックの課を完了してから複合母音を学んでください。"
    }
  };

  const COMBINE_QUESTIONS = [
    {id:'cp1',parts:'ㅗ + ㅏ',correct:'ㅘ',options:['ㅘ','ㅝ','ㅚ']},
    {id:'cp2',parts:'ㅜ + ㅓ',correct:'ㅝ',options:['ㅞ','ㅘ','ㅝ']},
    {id:'cp3',parts:'ㅗ + ㅣ',correct:'ㅚ',options:['ㅟ','ㅚ','ㅢ']},
    {id:'cp4',parts:'ㅜ + ㅣ',correct:'ㅟ',options:['ㅚ','ㅢ','ㅟ']},
    {id:'cp5',parts:'ㅡ + ㅣ',correct:'ㅢ',options:['ㅟ','ㅢ','ㅚ']}
  ];
  const SPLIT_QUESTIONS = [
    {id:'sp1',syllable:'와',correct:'ㅇ + ㅘ',options:['ㅇ + ㅘ','ㅇ + ㅙ','ㅗ + ㅏ']},
    {id:'sp2',syllable:'워',correct:'ㅇ + ㅝ',options:['ㅇ + ㅞ','ㅇ + ㅝ','ㅜ + ㅓ']},
    {id:'sp3',syllable:'뭐',correct:'ㅁ + ㅝ',options:['ㅁ + ㅘ','ㅁ + ㅝ','ㅇ + ㅝ']},
    {id:'sp4',syllable:'위',correct:'ㅇ + ㅟ',options:['ㅇ + ㅚ','ㅇ + ㅢ','ㅇ + ㅟ']}
  ];
  const SPELLING_QUESTIONS = [
    {id:'wr1',parts:'ㅗ + ㅐ',correct:'ㅙ',options:['ㅙ','ㅚ','ㅞ']},
    {id:'wr2',parts:'ㅗ + ㅣ',correct:'ㅚ',options:['ㅞ','ㅙ','ㅚ']},
    {id:'wr3',parts:'ㅜ + ㅔ',correct:'ㅞ',options:['ㅚ','ㅞ','ㅙ']}
  ];
  const WORDS = [
    {text:'과자',translation:'snack'},{text:'여우',translation:'fox'},{text:'의자',translation:'chair'},
    {text:'왜',translation:'why'},{text:'예',translation:'yes'},{text:'뭐',translation:'what'}
  ];
  const CHALLENGE = [
    {id:'c1',prompt:'c1',correct:'ㅘ',options:['ㅘ','ㅝ','ㅚ'],explain:'summary1'},
    {id:'c2',prompt:'c2',correct:'ㅜ + ㅓ',options:['ㅗ + ㅏ','ㅜ + ㅓ','ㅡ + ㅣ'],explain:'ueoLead'},
    {id:'c3',prompt:'c3',correct:'위',options:['외','위','의'],explain:'carrierLead'},
    {id:'c4',prompt:'c4',correct:'near',options:['extended','near','basic'],explain:'noFakeListening'},
    {id:'c5',prompt:'c5',correct:'과자',options:['여우','의자','과자'],explain:'wordsLead'}
  ];
  const OPTION_LABEL_KEYS = Object.freeze({near:'c4correct',extended:'ㅒ / ㅖ',basic:'ㅐ / ㅔ'});

  function languageFromEnvironment() { const requested=new URLSearchParams(global.location.search).get('lang'); if(LANGUAGES.includes(requested))return requested; const saved=global.NikigoState?.get?.().interfaceLanguage; if(LANGUAGES.includes(saved))return saved; const browser=(global.navigator?.language||'en').slice(0,2); return LANGUAGES.includes(browser)?browser:'en'; }
  let language=languageFromEnvironment();
  let profile=global.NikigoState?.get?.()||{completedLessons:[],lessonProgress:{},xp:0};
  let completionAwardedThisView=false;
  function text(key,values={}){let value=UI[language]?.[key]??UI.en[key]??String(key);for(const [name,replacement] of Object.entries(values))value=value.replaceAll(`{${name}}`,replacement);return value;}
  function rotate(values,offset){const copy=[...values];const amount=offset%copy.length;return [...copy.slice(amount),...copy.slice(0,amount)];}
  function optionOrders(){return Object.fromEntries(CHALLENGE.map((q,index)=>[q.id,rotate(q.options,index+1)]));}
  function blankSession(){return{step:0,completed:false,combineAnswers:{},built:[],builderInitial:'ㅇ',builderVowel:'ㅘ',splitAnswers:{},spellingAnswers:{},challengeStarted:false,challengeIndex:0,challengeAnswers:{},mistakes:[],retryAnswers:{},optionOrders:optionOrders()};}
  function normalizeSession(raw){const base=blankSession(),source=raw&&typeof raw==='object'?raw:{};return{...base,...source,step:Math.max(0,Math.min(SCREENS.length-1,Number(source.step)||0)),completed:source.completed===true,combineAnswers:{...(source.combineAnswers||{})},built:[...new Set((source.built||[]).filter(value=>Object.values(SAFE_SYLLABLES).includes(value)))],builderInitial:['ㅇ','ㅁ'].includes(source.builderInitial)?source.builderInitial:'ㅇ',builderVowel:['ㅘ','ㅙ','ㅚ','ㅝ','ㅞ','ㅟ','ㅢ'].includes(source.builderVowel)?source.builderVowel:'ㅘ',splitAnswers:{...(source.splitAnswers||{})},spellingAnswers:{...(source.spellingAnswers||{})},challengeStarted:source.challengeStarted===true,challengeIndex:Math.max(0,Math.min(CHALLENGE.length-1,Number(source.challengeIndex)||0)),challengeAnswers:{...(source.challengeAnswers||{})},mistakes:[...new Set((source.mistakes||[]).filter(id=>CHALLENGE.some(q=>q.id===id)))],retryAnswers:{...(source.retryAnswers||{})},optionOrders:Object.fromEntries(CHALLENGE.map(q=>[q.id,Array.isArray(source.optionOrders?.[q.id])&&source.optionOrders[q.id].length===q.options.length?[...source.optionOrders[q.id]]:optionOrders()[q.id]]))};}
  function readSession(){try{return normalizeSession(JSON.parse(global.localStorage.getItem(SESSION_KEY)||'{}'));}catch{return blankSession();}}
  let session=readSession();
  function isUnlocked(source){return new Set(source?.completedLessons||[]).has(PREREQUISITE);}
  function completionPatch(source){const completed=new Set(source.completedLessons||[]),first=!completed.has(LESSON_ID);completed.add(LESSON_ID);return{...source,completedLessons:[...completed],lessonProgress:{...(source.lessonProgress||{}),[LESSON_ID]:100},xp:(Number(source.xp)||0)+(first?50:0)};}
  function saveSession(){global.localStorage.setItem(SESSION_KEY,JSON.stringify(session));if(!session.completed&&isUnlocked(profile)){const percent=Math.min(99,Math.round(session.step/(SCREENS.length-1)*100));profile=global.NikigoState?.update?.(current=>({...current,lessonProgress:{...(current.lessonProgress||{}),[LESSON_ID]:Math.max(Number(current.lessonProgress?.[LESSON_ID])||0,percent)}}),'lesson-06:progress')||profile;}}
  function compoundFromParts(first,second){return COMBINATIONS[`${first}+${second}`]||'';}
  function carrierSyllable(vowel){return CARRIERS[vowel]||'';}
  function compose(initial,vowel){return SAFE_SYLLABLES[`${initial}+${vowel}`]||'';}
  function splitSyllable(syllable){const entry=Object.entries(SAFE_SYLLABLES).find(([,value])=>value===syllable);if(!entry)return null;const [initial,vowel]=entry[0].split('+');return{initial,vowel};}
  function answerQuestion(state,question,choice,answerKey){const next=normalizeSession(state);next[answerKey][question.id]={choice,correct:choice===question.correct};return next;}
  function applyChallengeAnswer(state,question,choice){const next=answerQuestion(state,question,choice,'challengeAnswers');if(choice!==question.correct&&!next.mistakes.includes(question.id))next.mistakes.push(question.id);return next;}
  function applyRetryAnswer(state,question,choice){const next=answerQuestion(state,question,choice,'retryAnswers');if(choice===question.correct)next.mistakes=next.mistakes.filter(id=>id!==question.id);return next;}
  function optionLabel(value){const key=OPTION_LABEL_KEYS[value];return key?text(key):value;}
  function footer({disabled=false,label=text('next'),action='next'}={}){return`<div class="foot"><button class="ghost" data-action="back">← ${text('back')}</button><button class="primary" data-action="${action}" ${disabled?'disabled':''}>${label} →</button></div>`;}
  function disabledAudio(kind,value){const label=kind==='word'?text('listenWord',{text:value}):text('listenSyllable',{text:value});return`<button class="audioPending" type="button" disabled aria-disabled="true" aria-label="${label} · ${text('audioPending')}">${label} · ${text('audioPending')}</button>`;}
  function renderIntro(){return`<span class="eyebrow">${text('introTag')}</span><h1>${text('introTitle')}</h1><p class="lead">${text('introLead')}</p><div class="goals">${[1,2,3].map(i=>`<div class="goal"><b>${text(`goal${i}`)}</b><span>${text(`goal${i}d`)}</span></div>`).join('')}</div><div class="note">${text('scopeNote')}</div>${footer()}`;}
  function renderReview(){return`<span class="eyebrow">${text('reviewTag')}</span><h1>${text('reviewTitle')}</h1><p class="lead">${text('reviewLead')}</p><div class="vowelGrid">${[['ㅐ','애'],['ㅔ','에']].map(([v,s])=>`<article class="vowelCard"><span class="vowelSymbol">${v}</span><strong>${s}</strong>${disabledAudio('syllable',s)}</article>`).join('')}</div><div class="reviewOnly">${text('audioNote')}</div>${footer()}`;}
  function equation(first,second,result,syllable){return`<div class="visualEquation"><span>${first}</span><b>+</b><span>${second}</span><b>=</b><span class="result">${result}</span></div>${syllable?`<div class="vowelCard"><small>${result} → ㅇ + ${result}</small><strong>${syllable}</strong>${disabledAudio('syllable',syllable)}</div>`:''}`;}
  function renderStructure(){return`<span class="eyebrow">${text('structureTag')}</span><h1>${text('structureTitle')}</h1><p class="lead">${text('structureLead')}</p><div class="combineGrid">${[['ㅗ','ㅏ','ㅘ'],['ㅜ','ㅓ','ㅝ'],['ㅡ','ㅣ','ㅢ']].map(([a,b,c])=>`<article class="combineCard"><span class="combineParts">${a} + ${b}</span><strong class="combineResult">${c}</strong></article>`).join('')}</div>${footer()}`;}
  function renderEquationScreen(kind){const isOa=kind==='oa';return`<span class="eyebrow">${text('structureTag')}</span><h1>${text(isOa?'oaTitle':'ueoTitle')}</h1><p class="lead">${text(isOa?'oaLead':'ueoLead')}</p>${equation(isOa?'ㅗ':'ㅜ',isOa?'ㅏ':'ㅓ',isOa?'ㅘ':'ㅝ',isOa?'와':'워')}<div class="reviewOnly">${text('audioNote')}</div>${footer()}`;}
  function renderIFamily(){return`<span class="eyebrow">${text('structureTag')}</span><h1>${text('familyTitle')}</h1><p class="lead">${text('familyLead')}</p><div class="combineGrid">${[['ㅗ','ㅣ','ㅚ'],['ㅜ','ㅣ','ㅟ'],['ㅡ','ㅣ','ㅢ']].map(([a,b,c])=>`<article class="combineCard"><span class="combineParts">${a} + ${b}</span><strong class="combineResult">${c}</strong></article>`).join('')}</div>${footer()}`;}
  function allCorrect(questions,key){return questions.every(q=>session[key][q.id]?.correct);}
  function renderQuestionRows(questions,key,action){return questions.map(q=>{const answer=session[key][q.id];return`<article class="practiceRow"><strong>${q.parts||q.syllable}</strong><div class="choiceRow">${q.options.map(value=>`<button class="${answer?(value===q.correct?'correct':value===answer.choice?'wrong':''):''}" data-action="${action}" data-question="${q.id}" data-value="${value}" ${answer?.correct?'disabled':''}>${value}${answer&&value===q.correct?' ✓':answer&&value===answer.choice?' ✕':''}</button>`).join('')}</div>${answer?`<div class="feedback ${answer.correct?'good':'try'}"><strong>${answer.correct?text('correct'):text('incorrect',{answer:q.correct})}</strong></div>`:''}</article>`;}).join('');}
  function renderCombinePractice(){return`<span class="eyebrow">${text('combineTag')}</span><h1>${text('combineTitle')}</h1><p class="lead">${text('combineLead')}</p><div class="combinePractice">${renderQuestionRows(COMBINE_QUESTIONS,'combineAnswers','combine-answer')}</div>${footer({disabled:!allCorrect(COMBINE_QUESTIONS,'combineAnswers')})}`;}
  function renderCarrier(){return`<span class="eyebrow">${text('carrierTag')}</span><h1>${text('carrierTitle')}</h1><p class="lead">${text('carrierLead')}</p><div class="vowelGrid">${COMPOUND_VOWELS.map(v=>`<article class="vowelCard"><span class="vowelSymbol">${v}</span><small>ㅇ + ${v}</small><strong>${CARRIERS[v]}</strong>${disabledAudio('syllable',CARRIERS[v])}</article>`).join('')}</div><div class="reviewOnly">${text('audioNote')}</div>${footer()}`;}
  function builderComplete(){return session.built.length>=3&&session.built.includes('뭐');}
  function renderBuilder(){const result=compose(session.builderInitial,session.builderVowel);return`<span class="eyebrow">${text('builderTag')}</span><h1>${text('builderTitle')}</h1><p class="lead">${text('builderLead')}</p><div class="builderPanel"><div class="builderGroup"><label>${text('initial')}</label><div class="builderChoices">${['ㅇ','ㅁ'].map(v=>`<button class="builderChoice ${session.builderInitial===v?'on':''}" data-action="builder-pick" data-kind="initial" data-value="${v}" aria-pressed="${session.builderInitial===v}">${v}</button>`).join('')}</div></div><b class="builderOperator">+</b><div class="builderGroup"><label>${text('vowel')}</label><div class="builderChoices">${['ㅘ','ㅙ','ㅚ','ㅝ','ㅞ','ㅟ','ㅢ'].map(v=>`<button class="builderChoice ${session.builderVowel===v?'on':''}" data-action="builder-pick" data-kind="vowel" data-value="${v}" aria-pressed="${session.builderVowel===v}">${v}</button>`).join('')}</div></div><b class="builderOperator">=</b><button class="builderResult" data-action="build" ${result?'':'disabled'} aria-label="${result?text('build',{text:result}):text('unsupported')}"><strong>${result||'—'}</strong><small>${result?text('build',{text:result}):text('unsupported')}</small></button></div><b>${text('built')}：</b><div class="builtSyllables">${session.built.map(v=>`<span>${v}</span>`).join('')||'—'}</div>${builderComplete()?'':`<div class="note">${text('builderNeed')}</div>`}${footer({disabled:!builderComplete()})}`;}
  function renderSplit(){return`<span class="eyebrow">${text('splitTag')}</span><h1>${text('splitTitle')}</h1><p class="lead">${text('splitLead')}</p><div class="splitGrid">${SPLIT_QUESTIONS.map(q=>{const answer=session.splitAnswers[q.id];return`<article class="splitQuestion"><div class="splitSyllable">${q.syllable}</div><div class="splitOptions">${q.options.map(value=>`<button class="${answer?(value===q.correct?'correct':value===answer.choice?'wrong':''):''}" data-action="split-answer" data-question="${q.id}" data-value="${value}" ${answer?.correct?'disabled':''}>${value}${answer&&value===q.correct?' ✓':answer&&value===answer.choice?' ✕':''}</button>`).join('')}</div></article>`;}).join('')}</div>${footer({disabled:!allCorrect(SPLIT_QUESTIONS,'splitAnswers')})}`;}
  function renderNearGroup(){return`<span class="eyebrow">${text('nearTag')}</span><h1>${text('nearTitle')}</h1><p class="lead">${text('nearLead')}</p><div class="spellingGrid">${[['ㅗ + ㅐ','ㅙ'],['ㅗ + ㅣ','ㅚ'],['ㅜ + ㅔ','ㅞ']].map(([p,v])=>`<article class="spellingCard"><small>${p}</small><strong class="vowelSymbol">${v}</strong></article>`).join('')}</div><div class="compareNotice">${text('noFakeListening')}</div>${footer()}`;}
  function renderSpelling(){return`<span class="eyebrow">${text('spellingTag')}</span><h1>${text('spellingTitle')}</h1><p class="lead">${text('spellingLead')}</p><div class="spellingGrid">${SPELLING_QUESTIONS.map(q=>{const answer=session.spellingAnswers[q.id];return`<article class="spellingCard"><h2>${q.parts}</h2><div class="spellingOptions">${q.options.map(value=>`<button class="${answer?(value===q.correct?'correct':value===answer.choice?'wrong':''):''}" data-action="spelling-answer" data-question="${q.id}" data-value="${value}" ${answer?.correct?'disabled':''}>${value}${answer&&value===q.correct?' ✓':answer&&value===answer.choice?' ✕':''}</button>`).join('')}</div></article>`;}).join('')}</div>${footer({disabled:!allCorrect(SPELLING_QUESTIONS,'spellingAnswers')})}`;}
  function renderExtended(){return`<span class="eyebrow">${text('extendedTag')}</span><h1>${text('extendedTitle')}</h1><p class="lead">${text('extendedLead')}</p><div class="vowelGrid">${[['ㅑ','ㅣ','ㅒ','얘'],['ㅕ','ㅣ','ㅖ','예']].map(([first,second,vowel,syllable])=>`<article class="vowelCard"><small class="compoundFormula">${first} + ${second} = ${vowel}</small><span class="vowelSymbol">${vowel}</span><strong>${syllable}</strong>${disabledAudio('syllable',syllable)}</article>`).join('')}</div><div class="compareNotice">${text('extendedNote')}</div>${footer()}`;}
  function renderWords(){return`<span class="eyebrow">${text('wordsTag')}</span><h1>${text('wordsTitle')}</h1><p class="lead">${text('wordsLead')}</p><div class="wordGrid06">${WORDS.map(word=>`<article class="wordCard06"><strong>${word.text}</strong><span class="translation">${text(word.translation)}</span>${disabledAudio('word',word.text)}</article>`).join('')}</div><div class="reviewOnly">${text('audioNote')}</div>${footer()}`;}
  function feedback(q,answer){return answer?`<div class="feedback ${answer.correct?'good':'try'}"><strong>${answer.correct?text('correct'):text('incorrect',{answer:optionLabel(q.correct)})}</strong><span>${text('correctAnswer')}：${optionLabel(q.correct)}</span><span>${text(q.explain)}</span></div>`:'';}
  function renderChallenge(){if(!session.challengeStarted)return`<div class="challengeHero"><div class="challengeIcon">◇</div><span class="eyebrow">${text('challengeTag')}</span><h1>${text('challengeTitle')}</h1><p class="lead centered">${text('challengeLead')}</p></div>${footer({label:text('startChallenge'),action:'start-challenge'})}`;const q=CHALLENGE[session.challengeIndex],answer=session.challengeAnswers[q.id],options=session.optionOrders[q.id];return`<div class="challengeHeader"><span class="eyebrow">${text('question')} · ${session.challengeIndex+1}/5</span><div class="questionDots">${CHALLENGE.map((_,i)=>`<i class="${i===session.challengeIndex?'on':''}"></i>`).join('')}</div></div><h1 class="practicePrompt">${text(q.prompt)}</h1><div class="challengeOptions">${options.map(value=>`<button class="challengeOption ${answer?(value===q.correct?'correct':value===answer.choice?'wrong':''):''}" data-action="challenge-answer" data-question="${q.id}" data-value="${value}" ${answer?'disabled':''}>${optionLabel(value)}${answer&&value===q.correct?' ✓':answer&&value===answer.choice?' ✕':''}</button>`).join('')}</div>${feedback(q,answer)}<div class="foot"><button class="ghost" data-action="${session.challengeIndex>0?'previous-question':'back'}">← ${session.challengeIndex>0?text('previousQuestion'):text('back')}</button><button class="primary" data-action="${session.challengeIndex<4?'next-question':'next'}" ${answer?'':'disabled'}>${session.challengeIndex<4?text('nextQuestion'):text('next')} →</button></div>`;}
  function renderRetry(){const id=session.mistakes[0];if(!id)return`<span class="eyebrow">${text('retryTag')}</span><h1>${text('retryTitle')}</h1><p class="lead">${text('retryLead')}</p><div class="note">✓ ${text('retryEmpty')}</div>${footer()}`;const q=CHALLENGE.find(item=>item.id===id),answer=session.retryAnswers[id],options=session.optionOrders[id];return`<span class="eyebrow">${text('retryTag')}</span><h1>${text('retryTitle')}</h1><p class="lead">${text('retryLead')}</p><div class="retryBadge">${text('remaining',{count:session.mistakes.length})}</div><h2 class="practicePrompt">${text(q.prompt)}</h2><div class="challengeOptions">${options.map(value=>`<button class="challengeOption ${answer?(value===q.correct?'correct':value===answer.choice?'wrong':''):''}" data-action="retry-answer" data-question="${q.id}" data-value="${value}" ${answer?'disabled':''}>${optionLabel(value)}${answer&&value===answer.choice?' ✕':''}</button>`).join('')}</div>${feedback(q,answer)}${answer&&!answer.correct?`<button class="secondary" data-action="retry-reset" data-question="${q.id}">↻ ${text('tryAgain')}</button>`:''}${footer({disabled:session.mistakes.length>0})}`;}
  function renderSummary(){return`<span class="eyebrow">${text('summaryTag')}</span><h1>${text('summaryTitle')}</h1><p class="lead">${text('summaryLead')}</p><div class="summaryList">${[1,2,3,4,5].map(i=>`<div>${i} · ${text(`summary${i}`)}</div>`).join('')}</div>${footer({label:text('finish')})}`;}
  function completeLesson(){if(session.completed)return false;const first=!new Set(profile.completedLessons||[]).has(LESSON_ID);session.completed=true;session.step=SCREENS.length-1;profile=global.NikigoState?.update?.(completionPatch,'lesson-06:complete')||completionPatch(profile);global.localStorage.setItem(SESSION_KEY,JSON.stringify(session));completionAwardedThisView=first;return first;}
  function renderComplete(){completeLesson();return`<div class="complete"><div class="completeMark">✓</div><span class="eyebrow">${text('completeTag')}</span><h1>${text('completeTitle')}</h1><p class="lead centered">${text('completeLead')}</p><div class="rewards"><span class="reward">✦ ${text(completionAwardedThisView?'xpEarned':'xpAlreadyClaimed')}</span><span class="reward">✓ ${text('progressSaved')}</span></div><button class="primary" data-action="home">${text('returnCourses')} →</button></div>`;}
  function renderLocked(){return`<div class="lockedPanel"><div class="completeMark">6</div><h1>${text('lockedTitle')}</h1><p class="lead centered">${text('lockedLead')}</p><button class="primary" data-action="home">${text('returnCourses')} →</button></div>`;}
  function allowed(type){if(type==='combine-practice')return allCorrect(COMBINE_QUESTIONS,'combineAnswers');if(type==='builder')return builderComplete();if(type==='split')return allCorrect(SPLIT_QUESTIONS,'splitAnswers');if(type==='spelling-practice')return allCorrect(SPELLING_QUESTIONS,'spellingAnswers');if(type==='retry')return session.mistakes.length===0;return true;}
  function render(){document.documentElement.lang=language==='zh'?'zh-CN':language;document.getElementById('language').value=language;document.getElementById('lessonName').textContent=text('lessonName');document.getElementById('progressLabel').textContent=text('progress');for(const id of ['homeButton','homeLogo']){document.getElementById(id).setAttribute('aria-label',text('home'));document.getElementById(id).title=text('home');}if(!isUnlocked(profile)){document.getElementById('progressCount').textContent='0 / 18';document.getElementById('progressBar').style.width='0%';document.getElementById('progressTrack').setAttribute('aria-valuenow','0');document.getElementById('lessonStage').innerHTML=renderLocked();return;}const percent=Math.round(session.step/(SCREENS.length-1)*100);document.getElementById('progressCount').textContent=`${session.step+1} / ${SCREENS.length}`;document.getElementById('progressBar').style.width=`${percent}%`;document.getElementById('progressTrack').setAttribute('aria-valuenow',String(percent));const type=SCREENS[session.step];const renderers={intro:renderIntro,review:renderReview,structure:renderStructure,oa:()=>renderEquationScreen('oa'),ueo:()=>renderEquationScreen('ueo'),'i-family':renderIFamily,'combine-practice':renderCombinePractice,carrier:renderCarrier,builder:renderBuilder,split:renderSplit,'near-group':renderNearGroup,'spelling-practice':renderSpelling,extended:renderExtended,words:renderWords,challenge:renderChallenge,retry:renderRetry,summary:renderSummary,complete:renderComplete};document.getElementById('lessonStage').innerHTML=renderers[type]();}
  function goHome(){global.location.href=`nikigo-app.html?lang=${language}#courses`;}
  document.addEventListener('click',event=>{const button=event.target.closest('button');if(!button)return;const action=button.dataset.action;if(button.id==='homeButton'||button.id==='homeLogo'||action==='home'){goHome();return;}if(!isUnlocked(profile))return;if(action==='back'){session.step=Math.max(0,session.step-1);}else if(action==='next'){const type=SCREENS[session.step];if(!allowed(type))return;session.step=Math.min(SCREENS.length-1,session.step+1);}else if(action==='combine-answer'){const q=COMBINE_QUESTIONS.find(item=>item.id===button.dataset.question);if(q&&!session.combineAnswers[q.id]?.correct)session=answerQuestion(session,q,button.dataset.value,'combineAnswers');}else if(action==='builder-pick'){if(button.dataset.kind==='initial')session.builderInitial=button.dataset.value;else session.builderVowel=button.dataset.value;}else if(action==='build'){const value=compose(session.builderInitial,session.builderVowel);if(value&&!session.built.includes(value))session.built.push(value);}else if(action==='split-answer'){const q=SPLIT_QUESTIONS.find(item=>item.id===button.dataset.question);if(q&&!session.splitAnswers[q.id]?.correct)session=answerQuestion(session,q,button.dataset.value,'splitAnswers');}else if(action==='spelling-answer'){const q=SPELLING_QUESTIONS.find(item=>item.id===button.dataset.question);if(q&&!session.spellingAnswers[q.id]?.correct)session=answerQuestion(session,q,button.dataset.value,'spellingAnswers');}else if(action==='start-challenge'){session.challengeStarted=true;}else if(action==='challenge-answer'){const q=CHALLENGE.find(item=>item.id===button.dataset.question);if(q&&!session.challengeAnswers[q.id])session=applyChallengeAnswer(session,q,button.dataset.value);}else if(action==='next-question'){if(!session.challengeAnswers[CHALLENGE[session.challengeIndex].id])return;session.challengeIndex=Math.min(4,session.challengeIndex+1);}else if(action==='previous-question'){session.challengeIndex=Math.max(0,session.challengeIndex-1);}else if(action==='retry-answer'){const q=CHALLENGE.find(item=>item.id===button.dataset.question);if(q&&!session.retryAnswers[q.id])session=applyRetryAnswer(session,q,button.dataset.value);}else if(action==='retry-reset'){delete session.retryAnswers[button.dataset.question];}saveSession();render();global.scrollTo(0,0);});
  document.getElementById('language').addEventListener('change',event=>{language=LANGUAGES.includes(event.target.value)?event.target.value:'en';profile=global.NikigoState?.update?.({interfaceLanguage:language,learningLanguage:language},'lesson-06:language')||profile;saveSession();render();});
  global.NikigoLesson06=Object.freeze({LESSON_ID,PREREQUISITE,SCREENS,UI,COMPOUND_VOWELS,COMBINATIONS,CARRIERS,SAFE_SYLLABLES,AUDIO_FILES,COMBINE_QUESTIONS,SPLIT_QUESTIONS,SPELLING_QUESTIONS,WORDS,CHALLENGE,compoundFromParts,carrierSyllable,compose,splitSyllable,blankSession,normalizeSession,applyChallengeAnswer,applyRetryAnswer,completionPatch,isUnlocked,getSession:()=>JSON.parse(JSON.stringify(session))});
  render();
})(window);
